name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master
on:
  push:
    branches: [ main ]
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.10.6
 
      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme
          python -m pip install sphinx-autoapi
          python -m pip install pydata-sphinx-theme
      - name: make the sphinx docs
        run: |
          make -C docs clean 
          make -C docs html

      - name: declare variables
        run: |
          pwd
          ls -lah
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)

      - name: update github pages 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"          

          docroot=`mktemp -d`
          rsync -av "docs/_build/html/" "${docroot}/"

          pushd "${docroot}"

          # don't bother maintaining history; just generate fresh
          git init
          git remote add deploy "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git checkout -b gh-pages

          touch .nojekyll
      
      - name: commit generated files
        run: |
          git add .
          msg="Updating Docs for commit ${GITHUB_SHA} made on `date -d"@${SOURCE_DATE_EPOCH}" --iso-8601=seconds` from ${GITHUB_REF} by ${GITHUB_ACTOR}"
          git commit -am "${msg}"
          git push deploy gh-pages --force

          popd
          exit 0

        # uses: ad-m/github-push-action@v0.5.0
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   branch: gh-pages
        #   force: true
        #   directory: ./docs/build/html